### ISSUE TITLE
Text Misaligned in VAB

### ISSUE THREAD

**Issue by UltraVioletUwU** [post-kerbin-mining-corporation/VABOrganizer#10] opened 2024-07-23 16:55 UTC
![image](https://github.com/user-attachments/assets/8eeecaf2-afee-467b-b40c-7d40f1379583)
[KSP.log](https://github.com/user-attachments/files/16352017/KSP.log)

**Comment by ChrisAdderley** [comment] 2024-07-23 17:30
Can't reproduce and that is way too many mods for me to try to track down.

Please provide screen resolution and all UI scale settings.

**Comment by UltraVioletUwU** [comment] 2024-07-23 17:35
Resolution is 3440 X 1440 full screen. UI scale all at default. If you can’t find a fix I will try to find out which other mod might be the problem, I don’t have many that should affect UI in theory.

**Comment by ChrisAdderley** [comment] 2024-07-23 17:53
Hmm yeah with those settings I still fail to reproduce the issue. Definitely see if you can reproduce it with less/no mods.

**Comment by UltraVioletUwU** [comment] 2024-07-24 01:53
I believe I have found the cause of the issue! It's, uhh, career mode? I made a clean install of KSP with no mods except for VABOrganizer and dependenci
es and the issue ONLY shows up in career mode saves, in sandbox and science mode the text in the vab is completely fine. Log: 


[KSP.log](https://github.com/user-attachments/files/16356052/KSP.log)

**Comment by ChrisAdderley** [comment] 2024-07-24 20:58
Ah ok I never play career so that makes sense. https://github.com/post-kerbin-mining-corporation/VABOrganizer/commit/d0d6aad55ead7aecbf4b849e0693285a1fc7123a has a fix for this. should work now

**Closed** 2024-07-24 21:28 UTC
